version: "3"

tasks:
  nats:
    cmds:
      - nats-server -D -js -m 8222 -sd deployments/data/nats
  linter-core:
    cmds:
      - dagger call linter --config build/ci/golangci.yaml --application-dir core/
  linter-core-fix:
    cmds:
      - dagger call linter --config build/ci/golangci.yaml --application-dir core/ --fix directory --path /app/ export --path core
