name: dagger

on:
  - pull_request

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: linter autochannelactivity
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          args: linter --config build/ci/golangci.yaml --application-dir . --directory autochannelactivity
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
