name: dagger

on:
  - pull_request

jobs:
  lint:
    name: lint
    uses: dagger/dagger-for-github@v5
    with:
      verb: call
      args: linter --config build/ci/golangci.yaml --application-dir . --directory core
      cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
