name: main

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Enable manual trigger for easier debugging
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/linter.yaml
    secrets: inherit
